package edu.grafos.aplicacao.trabalhoextraetapa2;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import edu.grafos.Grafo;
import edu.grafos.GrafoPonderado;
import edu.grafos.metodosdebusca.ponderado.ResultadoPonderado;
import edu.grafos.metodosdebusca.ponderado.ResultadoWarshall;

public class TrabalhoExtraEtapa2 {
	private JPanel root;
	private JLabel lbl1;
	private JTable tblDistancias;
	private JLabel lbl2;
	private JTable tblPredecessores;
	private JLabel lblRes;
	private JLabel lbl13;
	private ResultadoPonderado resultado;
	
	public static void main( String[] args ) {
		TrabalhoExtraEtapa2 app = new TrabalhoExtraEtapa2();
		JFrame frame = new JFrame( "Trabalho1Etapa1" );
		frame.setContentPane( app.root );
		frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
		frame.pack();
		frame.setVisible( true );
		frame.setLocationRelativeTo( null );
		frame.setSize( 400, 250 );
		app.lblRes.setText( app.resultado.menorCaminho( 12 ).toString() );
	}
	
	private void createUIComponents() {
		int NA = Grafo.INFINITO;
		int matriz[][] = new int[][] {
				//       a   b   c   d   e   f   g   h   i   j   l   m
				/*a*/ { NA, 61, 50, 42, NA, NA, NA, NA, NA, NA, NA, NA },
				/*b*/ { 61, NA, NA, 32, NA, 29, NA, NA, NA, 17, NA, NA },
				/*c*/ { 50, NA, NA, 56, 67, NA, NA, NA, NA, NA, NA, NA },
				/*d*/ { 42, 32, 56, NA, 45, 62, 85, NA, NA, NA, NA, NA },
				/*e*/ { NA, NA, 67, 45, NA, NA, 72, NA, 73, NA, NA, NA },
				/*f*/ { NA, 29, NA, 62, NA, NA, 20, 35, NA, 30, 45, NA },
				/*g*/ { NA, NA, NA, 85, 72, 20, NA, 40, 60, NA, NA, 32 },
				/*h*/ { NA, NA, NA, NA, NA, 35, 40, NA, NA, NA, 50, 21 },
				/*i*/ { NA, NA, NA, NA, 73, NA, 60, NA, NA, NA, NA, 50 },
				/*j*/ { NA, 17, NA, NA, NA, 30, NA, NA, NA, NA, 30, NA },
				/*l*/ { NA, NA, NA, NA, NA, 45, NA, 50, NA, 30, NA, NA },
				/*m*/ { NA, NA, NA, NA, NA, 32, NA, 21, 50, NA, NA, NA }
		};
		GrafoPonderado grafo = new GrafoPonderado( matriz, true );
		
		//Destino ignorado utilizando o algoritmo de Dijkstra
		resultado = (ResultadoPonderado) grafo.buscar( 1, GrafoPonderado.MetodoDeBusca.BELLMAN_FORD );
		//Definição dos dados a serem inseridos na tabela de distâncias
		Object[] colunas = { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "l", "m" };
		Object[] distancias = new Object[matriz.length];
		//Definição dos dados a serem inseridos na tabela de predecessores
		Object[] predecessores = new Object[matriz.length];
		//Transferir os dados da busca para os objetos a serem inseridos nas tabelas
		for ( int i = 0; i < resultado.getDistancias().length; i++ ) {
			distancias[i] = resultado.getDistancias()[i];
			predecessores[i] = resultado.getPredecessores()[i];
		}
		//Definir e popular as tabelas distâncias e predecessores
		tblDistancias = new JTable( new Object[][] { distancias }, colunas );
		tblPredecessores = new JTable( new Object[][] { predecessores }, colunas );
		
		System.out.println(
				( (ResultadoWarshall) grafo.buscar( 0, GrafoPonderado.MetodoDeBusca.FLOYD_WARSHALL ) )
						.menorCaminho( 1, 12 ) );
	}
	
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}
	
	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		root = new JPanel();
		root.setLayout( new GridBagLayout() );
		lbl1 = new JLabel();
		Font lbl1Font = this.$$$getFont$$$( "Consolas", Font.BOLD, 18, lbl1.getFont() );
		if ( lbl1Font != null ) {
			lbl1.setFont( lbl1Font );
		}
		lbl1.setText( "Tabela de distâncias" );
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		root.add( lbl1, gbc );
		lbl2 = new JLabel();
		Font lbl2Font = this.$$$getFont$$$( "Consolas", Font.BOLD, 18, lbl2.getFont() );
		if ( lbl2Font != null ) {
			lbl2.setFont( lbl2Font );
		}
		lbl2.setText( "Tabela de predecessores" );
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		root.add( lbl2, gbc );
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setHorizontalScrollBarPolicy( 31 );
		scrollPane1.setMinimumSize( new Dimension( 7, 38 ) );
		scrollPane1.setVerticalScrollBarPolicy( 21 );
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.anchor = GridBagConstraints.NORTH;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		root.add( scrollPane1, gbc );
		tblDistancias.setAutoResizeMode( 4 );
		tblDistancias.setFillsViewportHeight( false );
		scrollPane1.setViewportView( tblDistancias );
		final JScrollPane scrollPane2 = new JScrollPane();
		scrollPane2.setHorizontalScrollBarPolicy( 31 );
		scrollPane2.setMinimumSize( new Dimension( 7, 38 ) );
		scrollPane2.setVerticalScrollBarPolicy( 21 );
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.anchor = GridBagConstraints.NORTH;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		root.add( scrollPane2, gbc );
		scrollPane2.setViewportView( tblPredecessores );
		lbl13 = new JLabel();
		Font lbl13Font = this.$$$getFont$$$( "Consolas", Font.BOLD, 18, lbl13.getFont() );
		if ( lbl13Font != null ) {
			lbl13.setFont( lbl13Font );
		}
		lbl13.setText( "Caminho mais curto de a até m:" );
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.weightx = 1.0;
		root.add( lbl13, gbc );
		lblRes = new JLabel();
		Font lblResFont = this.$$$getFont$$$( "Consolas", Font.BOLD, 18, lblRes.getFont() );
		if ( lblResFont != null ) {
			lblRes.setFont( lblResFont );
		}
		lblRes.setText( "" );
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.weightx = 1.0;
		root.add( lblRes, gbc );
	}
	
	/** @noinspection ALL */
	private Font $$$getFont$$$( String fontName, int style, int size, Font currentFont ) {
		if ( currentFont == null ) {
			return null;
		}
		String resultName;
		if ( fontName == null ) {
			resultName = currentFont.getName();
		} else {
			Font testFont = new Font( fontName, Font.PLAIN, 10 );
			if ( testFont.canDisplay( 'a' ) && testFont.canDisplay( '1' ) ) {
				resultName = fontName;
			} else {
				resultName = currentFont.getName();
			}
		}
		return new Font( resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize() );
	}
	
	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() {
		return root;
	}
}
